on:
    workflow_call:
        inputs:
            appEnv:
                type: string
                required: true
            appUrl:
                type: string
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            runs-on: ubuntu-latest
            environment:
                name: ${{ inputs.appEnv }}
                url: ${{ inputs.appUrl }}
            timeout-minutes: 20
            steps:
                -   name: Checkout
                    uses: actions/checkout@v3
                -   uses: pnpm/action-setup@v2
                    with:
                        version: 7.14.2
                -   name: Use Node.js v16
                    uses: actions/setup-node@v3
                    with:
                        node-version: "16"
                        cache: "pnpm"
                -   name: Install dependencies
                    run: pnpm install

                -   name: Build
                    run: pnpm build
