name: production-deployment

concurrency:
    group: deploy-production
    cancel-in-progress: true

on:
    workflow_dispatch:
    release:
        types:
            - published

jobs:
    deploy_staging:
        uses: ./.github/workflows/job_deploy.yml
        with:
            appEnv: production
            appUrl: https://app.myapp.dev
