name: staging-deployment

concurrency:
    group: deploy-staging
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy_staging:
        uses: ./.github/workflows/deploy.yml
        with:
            appEnv: staging
            appUrl: https://staging.myapp.dev
