name: temp-env-cleanup

concurrency:
  group: temp-env-cleanup-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  delete:
    branches:
      - 'major/*'
      - 'hotfix/*'

jobs:
  cleanup:
    if: ${{ contains(github.event.ref, 'major/') || contains(github.event.ref, 'hotfix/') }}
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/950836167777/locations/global/workloadIdentityPools/github-actions/providers/deployment-provider'
          service_account: 'deployer@git-flow-poc.iam.gserviceaccount.com'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Set credentials
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}

      - name: remove service
        # github.event.ref: major/<feature-name>
        run: |
          temp_env_name=$(echo ${{ github.event.ref }} | cut -d '/' -f 2)
          echo "temp_env_name: $temp_env_name"
          gcloud app services delete $temp_env_name --quiet
